export const AUTH_LOGIN_GET: 'AUTH_LOGIN_GET' = 'AUTH_LOGIN_GET';
export const AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS' = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR' = 'AUTH_LOGIN_ERROR';
export const AUTH_REGISTER_GET: 'AUTH_REGISTER_GET' = 'AUTH_REGISTER_GET';
export const AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS' =
    'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR' = 'AUTH_REGISTER_ERROR';
export const AUTH_LOGOUT: 'AUTH_LOGOUT' = 'AUTH_LOGOUT';
export const AUTH_USER_REQUEST: 'AUTH_USER_REQUEST' = 'AUTH_USER_REQUEST';
export const AUTH_USER_SET_SUCCESS: 'AUTH_USER_SET_SUCCESS' =
    'AUTH_USER_SET_SUCCESS';
export const AUTH_USER_ERROR: 'AUTH_USER_ERROR' = 'AUTH_USER_ERROR';
export const AUTH_FORGOT_PASSWORD_SUCCESS: 'AUTH_FORGOT_PASSWORD_SUCCESS' =
    'AUTH_FORGOT_PASSWORD_SUCCESS';
export const AUTH_RESET_PASSWORD_SUCCESS: 'AUTH_RESET_PASSWORD_SUCCESS' =
    'AUTH_RESET_PASSWORD_SUCCESS';
