export const CONSTRUCTOR_ADD: 'CONSTRUCTOR_ADD' = 'CONSTRUCTOR_ADD';
export const CONSTRUCTOR_REMOVE: 'CONSTRUCTOR_REMOVE' = 'CONSTRUCTOR_REMOVE';
export const CONSTRUCTOR_REBUILD: 'CONSTRUCTOR_REBUILD' = 'CONSTRUCTOR_REBUILD';
export const CONSTRUCTOR_RESET: 'CONSTRUCTOR_RESET' = 'CONSTRUCTOR_RESET';
